language: python
python:
    - "2.7"

branches:
    only:
        - develop

install:
    - echo '3\n' | sudo python ./install/install.py
    - rm -rf ./tests
    - git clone https://github.com/owtf/owtf_testing tests

script:
    - sudo python -m unittest discover -s ./tests/tests_functional/cli -p "test_empty.py"
