language: python
python:
    - "2.7"

branches:
    only:
        - develop

sudo:
    - required

before_install:
    - sudo apt-get purge python-openssl
    - sudo apt-get install libffi-dev
    - sudo pip install pyopenssl

install:
    - echo '\n\n' | sudo python ./install/install.py
    - rm -rf ./tests
    - git clone https://github.com/owtf/owtf_testing
    - sudo pip install --upgrade --force-reinstall -r ./owtf_testing/owtf_testing.pip

before_script:
    - cp -f ./framework/config/web_testgroups.cfg ./framework/config/web_testgroups.cfg.backup
    - cp -f ./framework/config/net_testgroups.cfg ./framework/config/net_testgroups.cfg.backup
    - cp -f ./framework/config/aux_testgroups.cfg ./framework/config/aux_testgroups.cfg.backup
    - cp -f ./owtf_testing/framework/config/web_testgroups.cfg ./framework/config/web_testgroups.cfg
    - cp -f ./owtf_testing/framework/config/net_testgroups.cfg ./framework/config/net_testgroups.cfg
    - cp -f ./owtf_testing/framework/config/aux_testgroups.cfg ./framework/config/aux_testgroups.cfg
    - git config --global user.email "tasty@mac.test"
    - git config --global user.name "Tasty Test"
    - git am < ./owtf_testing/patch/0001-unittest-Patch-to-reuse-proxy-address.patch
    - ./owtf_testing/patch/skipfish.sh

script:
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_simulation.OWTFCliSimulationTest.test_cli_simulation
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_simulation.OWTFCliSimulationTest.test_cli_no_simulation

    - sudo python -m unittest owtf_testing.tests_functional.cli.test_nowebui.OWTFCliNoWebUITest.test_cli_no_webui

    - sudo python -m unittest owtf_testing.tests_functional.cli.test_empty_run.OWTFCliEmptyRunTest.test_cli_empty_run

    - sudo python -m unittest owtf_testing.tests_functional.cli.test_list_plugins.OWTFCliListPluginsTest.test_cli_list_plugins_aux
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_list_plugins.OWTFCliListPluginsTest.test_cli_list_plugins_net
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_list_plugins.OWTFCliListPluginsTest.test_cli_list_plugins_web

    - sudo python -m unittest owtf_testing.tests_functional.cli.test_only.OWTFCliOnlyPluginsTest.test_only_one_plugin
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_only.OWTFCliOnlyPluginsTest.test_only_one_plugin_one_type

    - sudo python -m unittest owtf_testing.tests_functional.cli.test_except.OWTFCliExceptTest.test_except

    - sudo python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_is_valid_ip
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_is_invalid
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_is_valid_http
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_are_mixed
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_are_mixed_but_web_specified
    - sudo python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_are_mixed_but_net_specified

    # TODO: Deactivated for now. Reactivate when #390 is fixed.
    #- sudo python -m unittest owtf_testing.tests_functional.cli.test_type.OWTFCliTypeTest.test_cli_type_web_default_active
    #- sudo python -m unittest owtf_testing.tests_functional.cli.test_type.OWTFCliTypeTest.test_cli_type_web_default_passive
    #- sudo python -m unittest owtf_testing.tests_functional.cli.test_type.OWTFCliTypeTest.test_cli_type_web_default_semi_passive
    #- sudo python -m unittest owtf_testing.tests_functional.cli.test_type.OWTFCliTypeTest.test_cli_type_net_default_bruteforce

    - sudo python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_active
    - sudo python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_passive
    - sudo python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_semi_passive
    - sudo python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_external
    - sudo python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_grep

    - sudo python -m unittest owtf_testing.tests_functional.plugins.web.active.test_web_active.OWTFCliWebActivePluginTest.test_web_active_wvs_001
    - sudo python -m unittest owtf_testing.tests_functional.plugins.web.active.test_web_active.OWTFCliWebActivePluginTest.test_web_active_wvs_006

after_script:
    - mv -f ./framework/config/web_testgroups.cfg.backup ./framework/config/web_testgroups.cfg
    - mv -f ./framework/config/net_testgroups.cfg.backup ./framework/config/net_testgroups.cfg
    - mv -f ./framework/config/aux_testgroups.cfg.backup ./framework/config/aux_testgroups.cfg

notifications:
    email: false
